# -*- coding: utf-8 -*-

MAX_FAILED_NUMBER=2
MAX_SELF_PLAY=2
MAX_ORIGIN_PLAY=3
MAX_SHARED_PLAY=20

PLAY_RESULT_SUCCESS = 1;
PLAY_RESULT_FAILED = -1;
PLAY_RESULT_INIT = 0;


SHARED_SUCCESS = 1
SHARED_INIT = 0
SHARED_CANCLE = -1